### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by wdhwg001** [jeremyhart/QuickLook.Plugin.FontViewer#3]
Currently every part of the font viewer are editable text fields, which feels a bit weird.

It would be best to lock all text fields and create another text field with placeholder "Type here to preview", so that users can type anything and the viewer will change the sample text to input string.

**Comment by jeremyhart** [comment]
I did that on purpose, as a graphic designer I use it all the time, this was one of the main reasons I made this plugin.

**Comment by wdhwg001** [comment]
Still, I think a separated text field is somehow certainly better and less buggy. And the "buggy" includes: pressing [Enter] in text fields will simply open the font file instead of adding a line break, and the copyright line is not rendered using the font but still editable.

Perhaps we can somehow freeze the title area, and fix the [Enter] bug in main text field?
